Moved SurfaceTension example to WorkInProgress (bad correlation)

diff --git a/hooks/pre-commit b/hooks/pre-commit
--- a/hooks/pre-commit
+++ b/hooks/pre-commit
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-## Check for file names with non-ascii characters.
+## Check for file names with non-ascii characters
 ## From pre-commit.sample
 if git rev-parse --verify HEAD >/dev/null 2>&1
 then
@@ -39,7 +39,7 @@ then
 fi
 
 
-## Run the Modelica parser (moparser) to check syntax.
+## Check for errors in the Modelica code.
 ## Based on http://www.sitepoint.com/git-hooks-fun-profit/
 git diff --cached --name-status --diff-filter=ACMR | while read STATUS FILE; do
 if [[ ${FILE: -3} == ".mo" ]]; then
@@ -50,6 +50,19 @@ if [[ ${FILE: -3} == ".mo" ]]; then
     fi
     if [ $? -ne 0 ]; then
         echo "Aborting commit due to files with syntax errors" >&2
+        exit 1
+    fi
+fi
+done
+
+
+## Check for errors in the Python code.
+## Based on http://www.sitepoint.com/git-hooks-fun-profit/
+git diff --cached --name-status --diff-filter=ACMR | while read STATUS FILE; do
+if [[ ${FILE: -3} == ".py" ]]; then
+    python -m py_compile "$FILE" 1> /dev/null
+    if [ $? -ne 0 ]; then
+        echo "Aborting commit due to errors in Python code" >&2
         exit 1
     fi
 fi
